// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwvpgilcocegoyomrdxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dnBnaWxjb2NlZ295b21yZHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzg2MTcsImV4cCI6MjA2NTkxNDYxN30.8DItyItoKWl4NXCrEQ3uqd87sGbrP9ahxgDOuvF3FGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);