// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imcrnxrnfmbujllvruuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltY3JueHJuZm1idWpsbHZydXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjkwNzMsImV4cCI6MjA2MjU0NTA3M30.sI1Ji9cyVjTqUYx66p1VqqkIUQJXsEwd3HbUmnUn3c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);